### ISSUE TITLE
Course content actualization

### ISSUE THREAD

**Issue by arsari** [mheap/mastering-express#1]
Hi,

I take this course through Lynda.com but some of the material is out of date.  the expect.js and instagram-node.js packages doesn't work.  Additionally, the instagram api connection has been changed.  When you expect to actualize the course or the material here in.

Thanks.
ASR

**Comment by mheap** [comment]
Hi ASR!

Sadly the course is many years old now and I do not intend to update the content.

Cheers, Michael
